create extension if not exists "pgcrypto";
create table if not exists public.task_lists (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null check (char_length(trim(name)) >= 3), position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), list_id uuid not null references public.task_lists(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, title text not null check (char_length(trim(title)) >= 3), description text, is_completed boolean not null default false, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.task_history (id uuid primary key default gen_random_uuid(), list_id uuid not null references public.task_lists(id) on delete cascade, task_id uuid references public.tasks(id) on delete set null, user_id uuid not null references auth.users(id) on delete cascade, action_type text not null, description text not null, created_at timestamptz not null default now());
alter table public.task_lists enable row level security; alter table public.tasks enable row level security; alter table public.task_history enable row level security;
create policy "Users manage own lists" on public.task_lists for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage own tasks" on public.tasks for all using (auth.uid() = user_id) with check (auth.uid() = user_id and exists (select 1 from public.task_lists l where l.id = list_id and l.user_id = auth.uid()));
create policy "Users manage own history" on public.task_history for all using (auth.uid() = user_id) with check (auth.uid() = user_id and exists (select 1 from public.task_lists l where l.id = list_id and l.user_id = auth.uid()));
create index if not exists idx_task_lists_user_position on public.task_lists(user_id, position); create index if not exists idx_tasks_list on public.tasks(list_id); create index if not exists idx_history_list_created on public.task_history(list_id, created_at desc);
