import { supabase } from '../lib/supabase/client';
import { HistoryAction, Task, TaskList } from '../types';

async function currentUserId() { const { data, error } = await supabase.auth.getUser(); if (error || !data.user) throw error ?? new Error('Usuário não autenticado.'); return data.user.id; }
async function addHistory(list_id:string, action_type:HistoryAction, description:string, task_id?:string|null) { const user_id = await currentUserId(); await supabase.from('task_history').insert({ list_id, task_id: task_id ?? null, user_id, action_type, description }); }
export async function fetchLists(): Promise<TaskList[]> { const user_id = await currentUserId(); const { data, error } = await supabase.from('task_lists').select('*, tasks(*)').eq('user_id', user_id).order('position'); if (error) throw error; return data ?? []; }
export async function saveList(name:string, list?:TaskList) { const user_id = await currentUserId(); if (list) { const { data, error } = await supabase.from('task_lists').update({ name, updated_at: new Date().toISOString() }).eq('id', list.id).select().single(); if (error) throw error; await addHistory(list.id, 'LIST_RENAMED', `Lista renomeada para ${name}`); return data; } const { count } = await supabase.from('task_lists').select('*', { count:'exact', head:true }).eq('user_id', user_id); const { data, error } = await supabase.from('task_lists').insert({ name, user_id, position: count ?? 0 }).select().single(); if (error) throw error; await addHistory(data.id, 'LIST_CREATED', `Lista ${name} criada`); return data; }
export async function deleteList(list:TaskList) { await addHistory(list.id, 'LIST_DELETED', `Lista ${list.name} excluída`); const { error } = await supabase.from('task_lists').delete().eq('id', list.id); if (error) throw error; }
export async function reorderLists(lists:TaskList[]) { await Promise.all(lists.map((l, position) => supabase.from('task_lists').update({ position }).eq('id', l.id))); }
export async function fetchTasks(listId:string): Promise<Task[]> { const { data, error } = await supabase.from('tasks').select('*').eq('list_id', listId).order('created_at', { ascending:false }); if (error) throw error; return data ?? []; }
export async function saveTask(listId:string, title:string, description:string, task?:Task) { const user_id = await currentUserId(); if (task) { const { data, error } = await supabase.from('tasks').update({ title, description, updated_at:new Date().toISOString() }).eq('id', task.id).select().single(); if (error) throw error; await addHistory(listId, 'TASK_UPDATED', `Atividade ${title} editada`, task.id); return data; } const { data, error } = await supabase.from('tasks').insert({ list_id:listId, user_id, title, description }).select().single(); if (error) throw error; await addHistory(listId, 'TASK_CREATED', `Atividade ${title} criada`, data.id); return data; }
export async function deleteTask(task:Task) { await addHistory(task.list_id, 'TASK_DELETED', `Atividade ${task.title} excluída`, task.id); const { error } = await supabase.from('tasks').delete().eq('id', task.id); if (error) throw error; }
export async function toggleTask(task:Task) { const next = !task.is_completed; const { error } = await supabase.from('tasks').update({ is_completed: next, completed_at: next ? new Date().toISOString() : null, updated_at:new Date().toISOString() }).eq('id', task.id); if (error) throw error; await addHistory(task.list_id, next ? 'TASK_COMPLETED':'TASK_REOPENED', next ? `Atividade ${task.title} concluída` : `Atividade ${task.title} marcada como pendente`, task.id); }
export async function setAllTasks(listId:string, completed:boolean) { const { error } = await supabase.from('tasks').update({ is_completed:completed, completed_at: completed ? new Date().toISOString() : null, updated_at:new Date().toISOString() }).eq('list_id', listId); if (error) throw error; await addHistory(listId, completed ? 'ALL_COMPLETED':'ALL_REOPENED', completed ? 'Todas as atividades foram concluídas' : 'Todas as atividades foram marcadas como pendentes'); }
export async function fetchHistory(listId:string) { const { data, error } = await supabase.from('task_history').select('*').eq('list_id', listId).order('created_at', { ascending:false }); if (error) throw error; return data ?? []; }
