import React from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from 'react-native';
import { useTheme } from '../hooks/useTheme';
export function Screen({ children }: { children: React.ReactNode }) { const { colors }=useTheme(); return <View style={[styles.screen,{backgroundColor:colors.bg}]}>{children}</View>; }
export function Card({ children }: { children: React.ReactNode }) { const { colors }=useTheme(); return <View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}>{children}</View>; }
export function AppText({ children, muted=false, title=false, style }: any) { const { colors }=useTheme(); return <Text style={[{color:muted?colors.muted:colors.text,fontSize:title?22:15,fontWeight:title?'700':'400'}, style]}>{children}</Text>; }
export function Button({ title, onPress, variant='primary' }: { title:string; onPress:()=>void; variant?:'primary'|'danger'|'ghost'|'success' }) { const { colors }=useTheme(); const bg = variant==='danger'?colors.danger:variant==='success'?colors.success:variant==='ghost'?'transparent':colors.primary; return <Pressable onPress={onPress} style={[styles.button,{backgroundColor:bg,borderColor:colors.border}]}><Text style={{color:variant==='ghost'?colors.text:'#fff',fontWeight:'700'}}>{title}</Text></Pressable>; }
export function Field({ label, error, ...props }: TextInputProps & { label:string; error?:string }) { const { colors }=useTheme(); return <View style={{gap:6}}><AppText>{label}</AppText><TextInput placeholderTextColor={colors.muted} style={[styles.input,{borderColor:error?colors.danger:colors.border,color:colors.text,backgroundColor:colors.card}]} {...props}/>{!!error && <AppText style={{color:colors.danger}}>{error}</AppText>}</View>; }
export function Loader() { return <View style={styles.center}><ActivityIndicator size="large" /></View>; }
const styles=StyleSheet.create({screen:{flex:1,padding:20,gap:16},card:{borderWidth:1,borderRadius:18,padding:16,gap:10,shadowOpacity:.06,shadowRadius:8},button:{padding:12,borderRadius:12,alignItems:'center',borderWidth:1},input:{borderWidth:1,borderRadius:12,padding:12},center:{flex:1,alignItems:'center',justifyContent:'center'}});
